global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'fantasy-ai-production'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'turbo-predictions'
    dns_sd_configs:
      - names:
          - 'tasks.turbo-predictions'
        type: 'A'
        port: 9090

  - job_name: 'websocket-cluster'
    dns_sd_configs:
      - names:
          - 'tasks.websocket-cluster'
        type: 'A'
        port: 9090

  - job_name: 'continuous-learning'
    dns_sd_configs:
      - names:
          - 'tasks.continuous-learning'
        type: 'A'
        port: 9090

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka-1:7071', 'kafka-2:7071', 'kafka-3:7071']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: 'traefik'
    static_configs:
      - targets: ['api-gateway:8080']