apiVersion: v1
kind: ConfigMap
metadata:
  name: fantasy-ai-config
  namespace: fantasy-ai
data:
  NODE_ENV: "production"
  PORT: "3000"
  WS_PORT: "8080"
  REDIS_URL: "redis://redis-service:6379"
  DATABASE_URL: "postgresql://postgres:postgres@postgres-service:5432/fantasy_ai"
  
  # ML Configuration
  ML_MODEL_PATH: "/models/production_model_v2"
  ML_BATCH_SIZE: "512"
  ML_CONFIDENCE_THRESHOLD: "0.7"
  
  # Service URLs
  WEBSOCKET_URL: "ws://websocket-service:8080"
  API_URL: "http://web-service:3000"
  
  # Monitoring
  ENABLE_METRICS: "true"
  METRICS_PORT: "9090"
  LOG_LEVEL: "info"