-- Step 2: Add columns to games and players tables
ALTER TABLE games ADD COLUMN IF NOT EXISTS scheduled_innings INTEGER DEFAULT 9;
ALTER TABLE games ADD COLUMN IF NOT EXISTS actual_innings INTEGER;
ALTER TABLE games ADD COLUMN IF NOT EXISTS game_type VARCHAR(10) DEFAULT 'R';
ALTER TABLE games ADD COLUMN IF NOT EXISTS doubleheader INTEGER DEFAULT 0;

ALTER TABLE players ADD COLUMN IF NOT EXISTS milb_status VARCHAR(20);
ALTER TABLE players ADD COLUMN IF NOT EXISTS draft_year INTEGER;
ALTER TABLE players ADD COLUMN IF NOT EXISTS draft_round INTEGER;
ALTER TABLE players ADD COLUMN IF NOT EXISTS signing_bonus NUMERIC;