apiVersion: apps/v1
kind: Deployment
metadata:
  name: fantasy-ai-pattern-system
  namespace: fantasy-ai
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pattern-api
  template:
    metadata:
      labels:
        app: pattern-api
    spec:
      containers:
      - name: pattern-api
        image: fantasyai/pattern-api:latest
        ports:
        - containerPort: 3338
        env:
        - name: NODE_ENV
          value: "production"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: fantasy-ai-secrets
              key: database-url
        - name: SUPABASE_SERVICE_ROLE_KEY
          valueFrom:
            secretKeyRef:
              name: fantasy-ai-secrets
              key: supabase-key
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /api/unified/stats
            port: 3338
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/unified/stats
            port: 3338
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: pattern-api-service
  namespace: fantasy-ai
spec:
  selector:
    app: pattern-api
  ports:
  - port: 3338
    targetPort: 3338
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pattern-stream
  namespace: fantasy-ai
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pattern-stream
  template:
    metadata:
      labels:
        app: pattern-stream
    spec:
      containers:
      - name: pattern-stream
        image: fantasyai/pattern-stream:latest
        ports:
        - containerPort: 3339
        - containerPort: 3340
        env:
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: pattern-stream-service
  namespace: fantasy-ai
spec:
  selector:
    app: pattern-stream
  ports:
  - name: http
    port: 3339
    targetPort: 3339
  - name: websocket
    port: 3340
    targetPort: 3340
  type: LoadBalancer
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: pattern-api-hpa
  namespace: fantasy-ai
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fantasy-ai-pattern-system
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80